[package]
name = "delouse"
version = "0.1.4"
edition = "2021"
license = "MIT"
authors = ["Paul Tagliamonte <paul@zoo.dev>"]
repository = "https://github.com/kittycad/delouse"
description = "delouse will expose opinionated debugging stubs most useful for tokio based async programs"

[dependencies]
anyhow = "1.0.75"
dropshot = { version = "0.10" }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "time", "io-util"] }
serde = "1.0"
serde_json = "1.0"
schemars = "0.8"
clap = { version = "4", features = ["cargo"] }
libc = "0.2"
elf = "0.7"
